services:
    pgdatabase:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=studentdb
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=student
        volumes:
            - "./studentdb:/var/lib/postgresql/data:rw"
    # pgadmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: root
    #     ports:
    #         - "8080:80"